---
# tasks file for ansible-role-consul

- name: Looking up latest version of Consul
  set_fact:
    consul_version: "{{ (lookup('url', 'https://api.github.com/repos/hashicorp/consul/releases/latest', split_lines=False) |
                    from_json).get('tag_name') | replace('v', '') }}"

- name: Ensure unzip is installed
  ansible.builtin.package:
    name: unzip
    state: present
  become: true

- name: Ensure python3 is installed
  ansible.builtin.package:
    name: python3
    state: present

- name: Install boto dependencies
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: 1
  become: true

- name: Download Consul package
  get_url:
    url: "{{ consul_zip_url }}"
    dest: "/tmp/{{ consul_pkg }}"
    timeout: "42"
  become: false
  tags: installation

- name: Unarchive and install Consul
  block:
    - name: Unarchive Consul package
      unarchive:
        src: "/tmp/{{ consul_pkg }}"
        dest: "{{ consul_bin_path }}/"
        creates: "{{ consul_bin_path }}/consul"
        remote_src: yes
      become: true
      tags:
        - installation
        - skip_ansible_lint
#  always:
#    - name: Cleanup
#      file:
#        path: "/tmp/{{ consul_pkg }}"
#        state: "absent"
#      become: false
#      vars:
#        ansible_become: false
#      tags: installation
#      ignore_errors: true

- name: Generate gossip encryption key
  shell: "{{ consul_bin_path }}/consul keygen"
  register: consul_keygen

- name: Create Consul Configuration folder
  ansible.builtin.file:
    path: "{{ consul_config_path }}"
    state: directory
    mode: '0755'

- name: Generate Consul Token
  shell: uuidgen > "{{ consul_config_path  }}/consul.token"
  run_once: true

- name: Set Consul Token as fact
  set_fact:
    consul_token: "{{lookup('ansible.builtin.file', '/etc/consul/consul.token') }}"
    remote_src: yes

- name: Create Consul Systemd Service
  ansible.builtin.template:
    src: templates/consul.service.j2
    dest: /lib/systemd/system/consul.service
    owner: root
    group: root
    mode: '0644'
  become: true
  register: systemd_unit

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: systemd_unit is changed

- name: Enable consul at startup (systemd)
  systemd:
    name: consul
    enabled: true

- name: Create Consul Configuration
  ansible.builtin.template:
    src: templates/config.json.j2
    dest: "{{ consul_config_path  }}/config.json"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Start consul service
  block:

    - name: Start Consul
      service:
        name: consul
        state: started
        enabled: true

- name: Save Consul Token to SSM
  community.aws.ssm_parameter:
    name: "consul-token-ansible_hostname"
    string_type: "SecureString"
    key_id: "{{ kms_key_id }}"
    value: "{{lookup('ansible.builtin.file', '/etc/consul/consul.token') }}"
    region: "us-east-1"
    remote_src: yes
  become_user: ubuntu
